site_name: Endgame
site_url: https://endgame.readthedocs.io/
repo_url: https://github.com/salesforce/endgame/
theme: material
use_directory_urls: true
markdown_extensions:
    - codehilite
    - tables
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - endgame/
extra_css:
  - custom.css
nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Tutorial: 'tutorial.md'
  - Detection: 'detection.md'
  - Prevention: 'prevention.md'
  - Recommendations To AWS: 'recommendations-to-aws.md'
  - Permissions: 'iam-permissions.md'

  - "<b>Backdoor Resource Types</b>":
    - ACM Private CAs: 'risks/acm-pca.md'
    - CloudWatch: 'risks/logs.md'
    - Elastic Block Store (EBS): 'risks/ebs.md'
    - EC2 Machine Images (AMIs): 'risks/amis.md'
    - Elastic Container Registry (ECR): 'risks/ecr.md'
    - Elastic File System (EFS): 'risks/efs.md'
    - ElasticSearch: 'risks/es.md'
    - Glacier Vaults: 'risks/glacier.md'
    - IAM Roles: 'risks/iam-roles.md'
    - KMS Keys: 'risks/kms.md'
    - Lambda Functions: 'risks/lambda-functions.md'
    - Lambda Layers: 'risks/lambda-layers.md'
    - RDS Snapshots: 'risks/rds-snapshots.md'
    - S3 Buckets: 'risks/s3.md'
    - Secrets Manager: 'risks/secretsmanager.md'
    - SES Authorized Senders: 'risks/ses.md'
    - SNS Topics: 'risks/sns.md'
    - SQS Queues: 'risks/sqs.md'

  - "<b>Contributing</b>":
    - Contributing: 'contributing/contributing.md'
    - Testing: 'contributing/testing.md'

  - "<b>Appendices</b>":
    - Terraform Demo Infrastructure: 'appendices/terraform-demo-infrastructure.md'
    - ACM PCA Activation: 'appendices/acm-pca-activation.md'
    - Roadmap: 'appendices/roadmap.md'
    - FAQ: 'appendices/faq.md'
    - Resource Policy Primer: 'resource-policy-primer.md'
